[package]
name = "ws"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
tokio = { version = "1.0", features = ["full"] }
aes-gcm = "0.10"
rpassword = "7.0"
dirs = "5.0"
rand = "0.8"
